c = input('digite algo = ')
print('O tipo primitivo desse valor é:', type(c))
print('Só tem espaços?', c.isspace())
print('É um número?', c.isnumeric())
print('É alfábetico?', c.isalpha())
print('É alfanúmerico?', c.isalnum())
print('Esta MAIUSCULO?', c.isupper())
print('Esta menuscula?', c.islower())
print('Esta captalizada?', c.istitle())
